# -*- coding: utf-8 -*-
"""
Baza 500 pytań AI Quiz - 50 pytań na każdą z 10 kategorii
Poziomy trudności: easy (łatwy), medium (średni), advanced (zaawansowany)
"""

AI_QUESTIONS_SEED = {
    "Historia powszechna": [
        # Łatwe (17 pytań)
        {"q": "W którym roku rozpoczęła się II wojna światowa?", "a": "1939", "b": "1941", "c": "1945", "correct": "A", "difficulty": "easy"},
        {"q": "Kto był pierwszym prezydentem USA?", "a": "Abraham Lincoln", "b": "George Washington", "c": "Thomas Jefferson", "correct": "B", "difficulty": "easy"},
        {"q": "W którym wieku żył Krzysztof Kolumb?", "a": "XIII", "b": "XIV", "c": "XV", "correct": "C", "difficulty": "easy"},
        {"q": "Które państwo zbudowało Wielki Mur Chiński?", "a": "Japonia", "b": "Chiny", "c": "Mongolia", "correct": "B", "difficulty": "easy"},
        {"q": "Kto był autorem 95 tez?", "a": "Jan Kalwin", "b": "Marcin Luter", "c": "Jan Hus", "correct": "B", "difficulty": "easy"},
        {"q": "W którym roku upadł Mur Berliński?", "a": "1987", "b": "1989", "c": "1991", "correct": "B", "difficulty": "easy"},
        {"q": "Kto był przywódcą ZSRR podczas II wojny światowej?", "a": "Lenin", "b": "Stalin", "c": "Chruszczow", "correct": "B", "difficulty": "easy"},
        {"q": "W którym roku człowiek wylądował na Księżycu?", "a": "1967", "b": "1969", "c": "1971", "correct": "B", "difficulty": "easy"},
        {"q": "Kto odkrył Amerykę?", "a": "Vasco da Gama", "b": "Ferdynand Magellan", "c": "Krzysztof Kolumb", "correct": "C", "difficulty": "easy"},
        {"q": "Która bitwa zakończyła się klęską Napoleona?", "a": "Austerlitz", "b": "Waterloo", "c": "Leipzig", "correct": "B", "difficulty": "easy"},
        {"q": "W którym roku zakończyła się I wojna światowa?", "a": "1917", "b": "1918", "c": "1919", "correct": "B", "difficulty": "easy"},
        {"q": "Kto był ostatnim carem Rosji?", "a": "Mikołaj I", "b": "Aleksander III", "c": "Mikołaj II", "correct": "C", "difficulty": "easy"},
        {"q": "W którym roku rozpadł się ZSRR?", "a": "1989", "b": "1991", "c": "1993", "correct": "B", "difficulty": "easy"},
        {"q": "Kto był premierem Wielkiej Brytanii podczas II wojny światowej?", "a": "Churchill", "b": "Chamberlain", "c": "Attlee", "correct": "A", "difficulty": "easy"},
        {"q": "W którym roku podpisano traktat wersalski?", "a": "1918", "b": "1919", "c": "1920", "correct": "B", "difficulty": "easy"},
        {"q": "Które miasto było stolicą Imperium Rzymskiego?", "a": "Ateny", "b": "Rzym", "c": "Konstantynopol", "correct": "B", "difficulty": "easy"},
        {"q": "Kto był założycielem religii islamu?", "a": "Budda", "b": "Jezus", "c": "Mahomet", "correct": "C", "difficulty": "easy"},

        # Średnie (17 pytań)
        {"q": "W którym roku odbyła się bitwa pod Grunwaldem?", "a": "1410", "b": "1420", "c": "1430", "correct": "A", "difficulty": "medium"},
        {"q": "Kto był cesarzem Francji po rewolucji francuskiej?", "a": "Ludwik XVI", "b": "Napoleon Bonaparte", "c": "Ludwik XVIII", "correct": "B", "difficulty": "medium"},
        {"q": "Które starożytne siedem cudów świata przetrwało do dziś?", "a": "Piramidy w Gizie", "b": "Kolos Rodyjski", "c": "Mauzoleum w Halikarnasie", "correct": "A", "difficulty": "medium"},
        {"q": "W którym roku rozpoczęła się rewolucja francuska?", "a": "1789", "b": "1799", "c": "1804", "correct": "A", "difficulty": "medium"},
        {"q": "Kto był liderem faszystowskich Włoch?", "a": "Victor Emmanuel", "b": "Benito Mussolini", "c": "Giuseppe Garibaldi", "correct": "B", "difficulty": "medium"},
        {"q": "Które imperium nazywano 'imperium, nad którym słońce nigdy nie zachodziło'?", "a": "Rzymskie", "b": "Brytyjskie", "c": "Osmańskie", "correct": "B", "difficulty": "medium"},
        {"q": "W którym roku nastąpiła rewolucja październikowa w Rosji?", "a": "1905", "b": "1917", "c": "1918", "correct": "B", "difficulty": "medium"},
        {"q": "Kto był ojcem rewolucji amerykańskiej?", "a": "George Washington", "b": "Benjamin Franklin", "c": "Thomas Jefferson", "correct": "A", "difficulty": "medium"},
        {"q": "Która dynastia rządziła Chinami najdłużej?", "a": "Ming", "b": "Qing", "c": "Zhou", "correct": "C", "difficulty": "medium"},
        {"q": "W którym roku nastąpił upadek Konstantynopola?", "a": "1453", "b": "1492", "c": "1517", "correct": "A", "difficulty": "medium"},
        {"q": "Kto był przywódcą III Rzeszy?", "a": "Hermann Göring", "b": "Adolf Hitler", "c": "Heinrich Himmler", "correct": "B", "difficulty": "medium"},
        {"q": "Która bitwa była największą bitwą pancerną II wojny światowej?", "a": "El Alamein", "b": "Kursk", "c": "Ardenach", "correct": "B", "difficulty": "medium"},
        {"q": "W którym roku odkryto Amerykę?", "a": "1492", "b": "1498", "c": "1502", "correct": "A", "difficulty": "medium"},
        {"q": "Kto był pierwszym cesarzem Rzymu?", "a": "Juliusz Cezar", "b": "August", "c": "Neron", "correct": "B", "difficulty": "medium"},
        {"q": "Która wojna trwała 100 lat?", "a": "Angielsko-francuska", "b": "Trojańska", "c": "Peloponeska", "correct": "A", "difficulty": "medium"},
        {"q": "W którym roku rozpoczęła się zimna wojna?", "a": "1945", "b": "1947", "c": "1950", "correct": "B", "difficulty": "medium"},
        {"q": "Kto był przywódcą Mongolii podczas największych podbojów?", "a": "Kubilaj-chan", "b": "Czyngis-chan", "c": "Timur", "correct": "B", "difficulty": "medium"},

        # Zaawansowane (16 pytań)
        {"q": "W którym roku nastąpiła bitwa pod Termopilami?", "a": "480 p.n.e.", "b": "490 p.n.e.", "c": "470 p.n.e.", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto był wodzem Kartaginy podczas II wojny punickiej?", "a": "Hannibal", "b": "Scypion Afrykański", "c": "Hamilkar Barka", "correct": "A", "difficulty": "advanced"},
        {"q": "Która dynastia rządziła Egiptem w okresie budowy piramid?", "a": "III", "b": "IV", "c": "V", "correct": "B", "difficulty": "advanced"},
        {"q": "W którym roku nastąpiła bitwa pod Akcjum?", "a": "31 p.n.e.", "b": "44 p.n.e.", "c": "27 p.n.e.", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto był ostatnim władcą Imperium Azteckiego?", "a": "Montezuma I", "b": "Montezuma II", "c": "Cuauhtémoc", "correct": "C", "difficulty": "advanced"},
        {"q": "W którym roku odbyła się bitwa pod Hastings?", "a": "1066", "b": "1086", "c": "1106", "correct": "A", "difficulty": "advanced"},
        {"q": "Która dynastia zjednoczyła Chiny po okresie Walczących Królestw?", "a": "Qin", "b": "Han", "c": "Zhou", "correct": "A", "difficulty": "advanced"},
        {"q": "W którym roku nastąpiło schizma wschodnia?", "a": "1054", "b": "1074", "c": "1094", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto był cesarzem Bizancjum podczas upadku Konstantynopola?", "a": "Konstantyn IX", "b": "Konstantyn XI", "c": "Konstantyn XII", "correct": "B", "difficulty": "advanced"},
        {"q": "Która bitwa zakończyła wojny napoleońskie ostatecznie?", "a": "Waterloo", "b": "Leipzig", "c": "Borodino", "correct": "A", "difficulty": "advanced"},
        {"q": "W którym roku nastąpiła reforma gregoriańska kalendarza?", "a": "1582", "b": "1592", "c": "1602", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto był dowódcą wojsk perskich w bitwie pod Maratonem?", "a": "Dariusz I", "b": "Kserkes", "c": "Artakserkes", "correct": "A", "difficulty": "advanced"},
        {"q": "Która bitwa była największą klęską legionów rzymskich?", "a": "Kannae", "b": "Teutoburski Las", "c": "Karrae", "correct": "B", "difficulty": "advanced"},
        {"q": "W którym roku nastąpiło zburzenie świątyni jerozolimskiej?", "a": "60 n.e.", "b": "70 n.e.", "c": "80 n.e.", "correct": "B", "difficulty": "advanced"},
        {"q": "Kto był ostatnim królem Babilonu?", "a": "Nabonid", "b": "Baltazar", "c": "Nebukadnesar II", "correct": "A", "difficulty": "advanced"},
        {"q": "Która dynastia chińska zbudowała Wielki Mur?", "a": "Qin", "b": "Han", "c": "Ming", "correct": "A", "difficulty": "advanced"},
    ],

    "Geografia": [
        # Łatwe
        {"q": "Która rzeka jest najdłuższa na świecie?", "a": "Nil", "b": "Amazonka", "c": "Jangcy", "correct": "A", "difficulty": "easy"},
        {"q": "Jaka jest stolica Francji?", "a": "Lyon", "b": "Marsylia", "c": "Paryż", "correct": "C", "difficulty": "easy"},
        {"q": "Na którym kontynencie znajduje się Egipt?", "a": "Azja", "b": "Afryka", "c": "Europa", "correct": "B", "difficulty": "easy"},
        {"q": "Która góra jest najwyższa na świecie?", "a": "K2", "b": "Mount Everest", "c": "Kilimandżaro", "correct": "B", "difficulty": "easy"},
        {"q": "Który ocean jest największy?", "a": "Atlantycki", "b": "Indyjski", "c": "Spokojny", "correct": "C", "difficulty": "easy"},
        {"q": "Jaka jest stolica Włoch?", "a": "Mediolan", "b": "Rzym", "c": "Wenecja", "correct": "B", "difficulty": "easy"},
        {"q": "W którym kraju znajduje się Wielki Kanion?", "a": "Meksyk", "b": "Kanada", "c": "USA", "correct": "C", "difficulty": "easy"},
        {"q": "Która pustynia jest największa na świecie?", "a": "Sahara", "b": "Gobi", "c": "Antarktyda", "correct": "C", "difficulty": "easy"},
        {"q": "Jaka jest stolica Hiszpanii?", "a": "Barcelona", "b": "Madryt", "c": "Sewilla", "correct": "B", "difficulty": "easy"},
        {"q": "Który kontynent jest najmniejszy?", "a": "Europa", "b": "Australia", "c": "Antarktyda", "correct": "B", "difficulty": "easy"},
        {"q": "W którym kraju znajduje się Wieża Eiffla?", "a": "Niemcy", "b": "Francja", "c": "Belgia", "correct": "B", "difficulty": "easy"},
        {"q": "Która rzeka przepływa przez Londyn?", "a": "Sekwana", "b": "Ren", "c": "Tamiza", "correct": "C", "difficulty": "easy"},
        {"q": "Jaka jest stolica Niemiec?", "a": "Monachium", "b": "Berlin", "c": "Hamburg", "correct": "B", "difficulty": "easy"},
        {"q": "Na którym kontynencie leży Brazylia?", "a": "Ameryka Południowa", "b": "Ameryka Północna", "c": "Afryka", "correct": "A", "difficulty": "easy"},
        {"q": "Która wyspa jest największa na świecie?", "a": "Madagaskar", "b": "Grenlandia", "c": "Borneo", "correct": "B", "difficulty": "easy"},
        {"q": "W którym kraju znajduje się Statua Wolności?", "a": "Kanada", "b": "USA", "c": "Francja", "correct": "B", "difficulty": "easy"},
        {"q": "Jaka jest stolica Rosji?", "a": "Sankt Petersburg", "b": "Moskwa", "c": "Kijów", "correct": "B", "difficulty": "easy"},

        # Średnie
        {"q": "Który kraj ma najwięcej stref czasowych?", "a": "Rosja", "b": "USA", "c": "Francja", "correct": "C", "difficulty": "medium"},
        {"q": "Jaka jest stolica Australii?", "a": "Sydney", "b": "Melbourne", "c": "Canberra", "correct": "C", "difficulty": "medium"},
        {"q": "Która rzeka jest najdłuższa w Europie?", "a": "Dunaj", "b": "Wołga", "c": "Ren", "correct": "B", "difficulty": "medium"},
        {"q": "W którym kraju znajduje się Angkor Wat?", "a": "Tajlandia", "b": "Kambodża", "c": "Wietnam", "correct": "B", "difficulty": "medium"},
        {"q": "Która zatoka jest największa na świecie?", "a": "Zatoka Perska", "b": "Zatoka Bengalska", "c": "Zatoka Meksykańska", "correct": "B", "difficulty": "medium"},
        {"q": "Jaka jest stolica Kanady?", "a": "Toronto", "b": "Vancouver", "c": "Ottawa", "correct": "C", "difficulty": "medium"},
        {"q": "Który kraj ma najdłuższą linię brzegową?", "a": "Rosja", "b": "Kanada", "c": "Indonezja", "correct": "B", "difficulty": "medium"},
        {"q": "W którym kraju znajduje się Petra?", "a": "Egipt", "b": "Jordania", "c": "Syria", "correct": "B", "difficulty": "medium"},
        {"q": "Która cieśnina łączy Morze Śródziemne z Oceanem Atlantyckim?", "a": "Gibraltar", "b": "Bosfor", "c": "Ormuz", "correct": "A", "difficulty": "medium"},
        {"q": "Jaka jest stolica Turcji?", "a": "Stambuł", "b": "Ankara", "c": "Izmir", "correct": "B", "difficulty": "medium"},
        {"q": "Który wodospad jest najwyższy na świecie?", "a": "Niagara", "b": "Wiktoria", "c": "Angel", "correct": "C", "difficulty": "medium"},
        {"q": "W którym kraju znajduje się jezioro Titicaca?", "a": "Chile", "b": "Peru i Boliwia", "c": "Argentyna", "correct": "B", "difficulty": "medium"},
        {"q": "Która pustynia znajduje się w Azji?", "a": "Sahara", "b": "Gobi", "c": "Kalahari", "correct": "B", "difficulty": "medium"},
        {"q": "Jaka jest stolica Brazylii?", "a": "Rio de Janeiro", "b": "São Paulo", "c": "Brasília", "correct": "C", "difficulty": "medium"},
        {"q": "Który kraj nazywa się 'Krajem Tysiąca Jezior'?", "a": "Szwecja", "b": "Finlandia", "c": "Norwegia", "correct": "B", "difficulty": "medium"},
        {"q": "W którym kraju znajduje się Mount Kilimanjaro?", "a": "Kenia", "b": "Tanzania", "c": "Uganda", "correct": "B", "difficulty": "medium"},
        {"q": "Która rzeka tworzy Gran Canyon?", "a": "Missouri", "b": "Kolorado", "c": "Rio Grande", "correct": "B", "difficulty": "medium"},

        # Zaawansowane
        {"q": "Który kraj ma najniższy punkt na lądzie?", "a": "Izrael", "b": "Jordania", "c": "Etiopia", "correct": "A", "difficulty": "advanced"},
        {"q": "Jaka jest stolica Kazachstanu od 2019 roku?", "a": "Ałmaty", "b": "Astana", "c": "Nur-Sułtan", "correct": "C", "difficulty": "advanced"},
        {"q": "Który punkt Ziemi jest najdalej od centrum?", "a": "Mount Everest", "b": "Chimborazo", "c": "K2", "correct": "B", "difficulty": "advanced"},
        {"q": "W którym kraju znajduje się jezioro Bajkał?", "a": "Mongolia", "b": "Rosja", "c": "Chiny", "correct": "B", "difficulty": "advanced"},
        {"q": "Która linia brezegovego jest najdłuższa?", "a": "Rosja", "b": "Kanada", "c": "Indonezja", "correct": "B", "difficulty": "advanced"},
        {"q": "Jaka jest stolica Bhutanu?", "a": "Thimphu", "b": "Paro", "c": "Punakha", "correct": "A", "difficulty": "advanced"},
        {"q": "Który kraj ma najwięcej wulkanów aktywnych?", "a": "Japonia", "b": "Indonezja", "c": "USA", "correct": "B", "difficulty": "advanced"},
        {"q": "W którym kraju znajduje się rów Mariański?", "a": "Filipiny", "b": "Japonia", "c": "Ocean Spokojny (wody międzynarodowe)", "correct": "C", "difficulty": "advanced"},
        {"q": "Która rzeka ma największą deltę na świecie?", "a": "Amazon", "b": "Ganges-Brahmaputra", "c": "Mekong", "correct": "B", "difficulty": "advanced"},
        {"q": "Jaka jest stolica Erytrei?", "a": "Asmara", "b": "Massawa", "c": "Keren", "correct": "A", "difficulty": "advanced"},
        {"q": "Który kontynent ma najwięcej krajów?", "a": "Azja", "b": "Afryka", "c": "Europa", "correct": "B", "difficulty": "advanced"},
        {"q": "W którym kraju znajduje się Salar de Uyuni?", "a": "Chile", "b": "Peru", "c": "Boliwia", "correct": "C", "difficulty": "advanced"},
        {"q": "Która cieśnina oddziela Azję od Ameryki?", "a": "Beringa", "b": "Drake'a", "c": "Magellana", "correct": "A", "difficulty": "advanced"},
        {"q": "Jaka jest stolica Surinamu?", "a": "Georgetown", "b": "Paramaribo", "c": "Cayenne", "correct": "B", "difficulty": "advanced"},
        {"q": "Który kraj ma najdłuższą granicę lądową?", "a": "Rosja-Kazachstan", "b": "USA-Kanada", "c": "Rosja-Mongolia", "correct": "A", "difficulty": "advanced"},
        {"q": "W którym kraju znajduje się najgłębsze jezioro?", "a": "Rosja", "b": "Kanada", "c": "USA", "correct": "A", "difficulty": "advanced"},
    ],

    "Znane postaci": [
        {"q": "Kto namalował Mona Lisę?", "a": "Michał Anioł", "b": "Leonardo da Vinci", "c": "Rafael", "correct": "B", "difficulty": "easy"},
        {"q": "Kto napisał 'Romeo i Julia'?", "a": "William Shakespeare", "b": "Charles Dickens", "c": "Jane Austen", "correct": "A", "difficulty": "easy"},
        {"q": "Kto był pierwszym człowiekiem w kosmosie?", "a": "Neil Armstrong", "b": "Jurij Gagarin", "c": "Buzz Aldrin", "correct": "B", "difficulty": "easy"},
        {"q": "Kto wynalazł żarówkę?", "a": "Nikola Tesla", "b": "Thomas Edison", "c": "Benjamin Franklin", "correct": "B", "difficulty": "medium"},
        {"q": "Kto skomponował 'Dla Elizy'?", "a": "Mozart", "b": "Beethoven", "c": "Chopin", "correct": "B", "difficulty": "medium"},
        {"q": "Kto był pierwszym prezydentem Polski?", "a": "Ignacy Paderewski", "b": "Gabriel Narutowicz", "c": "Stanisław Wojciechowski", "correct": "B", "difficulty": "medium"},
        {"q": "Kto odkrył penicylinę?", "a": "Louis Pasteur", "b": "Alexander Fleming", "c": "Marie Curie", "correct": "B", "difficulty": "advanced"},
        {"q": "Kto namalował 'Gwiaździstą noc'?", "a": "Vincent van Gogh", "b": "Pablo Picasso", "c": "Claude Monet", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto był autorem teorii względności?", "a": "Isaac Newton", "b": "Albert Einstein", "c": "Stephen Hawking", "correct": "B", "difficulty": "advanced"},
        {"q": "Kto otrzymał Nobla w dziedzinie chemii i fizyki?", "a": "Marie Curie", "b": "Linus Pauling", "c": "Albert Einstein", "correct": "A", "difficulty": "advanced"},
    ],

    "Muzyka": [
        {"q": "Kto był liderem zespołu The Beatles?", "a": "Paul McCartney", "b": "John Lennon", "c": "George Harrison", "correct": "B", "difficulty": "easy"},
        {"q": "Który kompozytor skomponował 'Cztery pory roku'?", "a": "Bach", "b": "Mozart", "c": "Vivaldi", "correct": "C", "difficulty": "easy"},
        {"q": "Ile strun ma standardowa gitara?", "a": "5", "b": "6", "c": "7", "correct": "B", "difficulty": "easy"},
        {"q": "Kto skomponował 'Mazurek Dąbrowskiego'?", "a": "Fryderyk Chopin", "b": "Józef Wybicki", "c": "Michał Kleofas Ogiński", "correct": "B", "difficulty": "medium"},
        {"q": "Który zespół wykonał 'Bohemian Rhapsody'?", "a": "Queen", "b": "Led Zeppelin", "c": "Pink Floyd", "correct": "A", "difficulty": "medium"},
        {"q": "Ile klawiszy ma standardowe pianino?", "a": "76", "b": "88", "c": "96", "correct": "B", "difficulty": "medium"},
        {"q": "Kto skomponował operę 'Don Giovanni'?", "a": "Verdi", "b": "Mozart", "c": "Wagner", "correct": "B", "difficulty": "advanced"},
        {"q": "Który kompozytor był głuchy?", "a": "Bach", "b": "Beethoven", "c": "Handel", "correct": "B", "difficulty": "advanced"},
        {"q": "Ile symfonii skomponował Beethoven?", "a": "9", "b": "10", "c": "12", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto napisał 'Marsz weselny'?", "a": "Wagner", "b": "Mendelssohn", "c": "Strauss", "correct": "B", "difficulty": "advanced"},
    ],

    "Literatura": [
        {"q": "Kto napisał 'Pan Tadeusz'?", "a": "Juliusz Słowacki", "b": "Adam Mickiewicz", "c": "Henryk Sienkiewicz", "correct": "B", "difficulty": "easy"},
        {"q": "Który pisarz stworzył Sherlocka Holmesa?", "a": "Agatha Christie", "b": "Arthur Conan Doyle", "c": "Edgar Allan Poe", "correct": "B", "difficulty": "easy"},
        {"q": "Kto napisał 'Władcę Pierścieni'?", "a": "C.S. Lewis", "b": "J.R.R. Tolkien", "c": "George R.R. Martin", "correct": "B", "difficulty": "easy"},
        {"q": "Kto napisał 'Quo Vadis'?", "a": "Bolesław Prus", "b": "Henryk Sienkiewicz", "c": "Stefan Żeromski", "correct": "B", "difficulty": "medium"},
        {"q": "Który poeta napisał 'Nie pytaj mnie, jak było tam'?", "a": "Wisława Szymborska", "b": "Czesław Miłosz", "c": "Zbigniew Herbert", "correct": "C", "difficulty": "medium"},
        {"q": "Kto napisał '1984'?", "a": "Aldous Huxley", "b": "George Orwell", "c": "Ray Bradbury", "correct": "B", "difficulty": "medium"},
        {"q": "Kto napisał 'Ferdydurke'?", "a": "Witold Gombrowicz", "b": "Bruno Schulz", "c": "Stanisław Lem", "correct": "A", "difficulty": "advanced"},
        {"q": "Który polski poeta otrzymał Nobla w 1980?", "a": "Wisława Szymborska", "b": "Czesław Miłosz", "c": "Zbigniew Herbert", "correct": "B", "difficulty": "advanced"},
        {"q": "Kto napisał 'Lalka'?", "a": "Henryk Sienkiewicz", "b": "Bolesław Prus", "c": "Eliza Orzeszkowa", "correct": "B", "difficulty": "advanced"},
        {"q": "Kto jest autorem 'Wesela'?", "a": "Stanisław Wyspiański", "b": "Juliusz Słowacki", "c": "Cyprian Norwid", "correct": "A", "difficulty": "advanced"},
    ],

    "Kuchnia": [
        {"q": "Z jakiego kraju pochodzi sushi?", "a": "Chiny", "b": "Japonia", "c": "Korea", "correct": "B", "difficulty": "easy"},
        {"q": "Który składnik jest głównym w guacamole?", "a": "Pomidor", "b": "Cebula", "c": "Awokado", "correct": "C", "difficulty": "easy"},
        {"q": "Z czego robi się makaron?", "a": "Ryż", "b": "Pszenica", "c": "Kukurydza", "correct": "B", "difficulty": "easy"},
        {"q": "Która kuchnia słynie z paelli?", "a": "Włoska", "b": "Hiszpańska", "c": "Portugalska", "correct": "B", "difficulty": "medium"},
        {"q": "Z czego robi się humus?", "a": "Ciecierzyca", "b": "Fasola", "c": "Soczewica", "correct": "A", "difficulty": "medium"},
        {"q": "Który ser jest tradycyjnie używany w pizza Margherita?", "a": "Parmezan", "b": "Mozzarella", "c": "Gorgonzola", "correct": "B", "difficulty": "medium"},
        {"q": "Co to jest roux w kuchni francuskiej?", "a": "Sos", "b": "Ciasto", "c": "Zagęszczacz z mąki i tłuszczu", "correct": "C", "difficulty": "advanced"},
        {"q": "Która przyprava jest najdroższa na świecie?", "a": "Wanilia", "b": "Szafran", "c": "Kardamon", "correct": "B", "difficulty": "advanced"},
        {"q": "Co to jest mise en place?", "a": "Francuski deser", "b": "Przygotowanie składników", "c": "Technika gotowania", "correct": "B", "difficulty": "advanced"},
        {"q": "Która kuchnia słynie z kimchi?", "a": "Japońska", "b": "Chińska", "c": "Koreańska", "correct": "C", "difficulty": "advanced"},
    ],

    "Film": [
        {"q": "Kto wyreżyserował 'Ojca chrzestnego'?", "a": "Martin Scorsese", "b": "Francis Ford Coppola", "c": "Steven Spielberg", "correct": "B", "difficulty": "easy"},
        {"q": "Który aktor grał Jamesa Bonda najdłużej?", "a": "Sean Connery", "b": "Roger Moore", "c": "Daniel Craig", "correct": "B", "difficulty": "easy"},
        {"q": "W którym roku powstał pierwszy film o Harrym Potterze?", "a": "1999", "b": "2001", "c": "2003", "correct": "B", "difficulty": "easy"},
        {"q": "Kto wyreżyserował 'Listę Schindlera'?", "a": "Steven Spielberg", "b": "Martin Scorsese", "c": "Francis Ford Coppola", "correct": "A", "difficulty": "medium"},
        {"q": "Który film otrzymał najwięcej Oscarów (11)?", "a": "Titanic", "b": "Ben-Hur", "c": "Oba odpowiedzi są poprawne", "correct": "C", "difficulty": "medium"},
        {"q": "Kto grał główną rolę w 'Pianista'?", "a": "Adrien Brody", "b": "Ralph Fiennes", "c": "Liam Neeson", "correct": "A", "difficulty": "medium"},
        {"q": "Kto wyreżyserował 'Siedem samurajów'?", "a": "Akira Kurosawa", "b": "Yasujirō Ozu", "c": "Kenji Mizoguchi", "correct": "A", "difficulty": "advanced"},
        {"q": "Który film otworzył festiwal w Cannes w 1994?", "a": "Pulp Fiction", "b": "Forrest Gump", "c": "Cztery wesela i pogrzeb", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto skomponował muzykę do 'Gwiezdnych wojen'?", "a": "Hans Zimmer", "b": "John Williams", "c": "Ennio Morricone", "correct": "B", "difficulty": "advanced"},
        {"q": "Który polski film zdobył Oscara?", "a": "Pianista", "b": "Ida", "c": "Oba odpowiedzi są poprawne", "correct": "C", "difficulty": "advanced"},
    ],

    "Nauki ścisłe": [
        {"q": "Jaki jest symbol chemiczny złota?", "a": "Go", "b": "Au", "c": "Gd", "correct": "B", "difficulty": "easy"},
        {"q": "Ile planet jest w Układzie Słonecznym?", "a": "8", "b": "9", "c": "10", "correct": "A", "difficulty": "easy"},
        {"q": "Jaka jest stolica matematyki?", "a": "0", "b": "1", "c": "Pi", "correct": "B", "difficulty": "easy"},
        {"q": "Jak nazywa się proces, w którym rośliny produkują tlen?", "a": "Respiracja", "b": "Fotosynteza", "c": "Transpiracja", "correct": "B", "difficulty": "medium"},
        {"q": "Ile wynosi przybliżona wartość liczby Pi?", "a": "3.14", "b": "3.16", "c": "3.18", "correct": "A", "difficulty": "medium"},
        {"q": "Który pierwiastek ma symbol Fe?", "a": "Fluor", "b": "Żelazo", "c": "Fosfor", "correct": "B", "difficulty": "medium"},
        {"q": "Kto sformułował prawa dynamiki?", "a": "Galileusz", "b": "Newton", "c": "Einstein", "correct": "B", "difficulty": "advanced"},
        {"q": "Jak nazywa się najlżejszy pierwiastek?", "a": "Hel", "b": "Wodór", "c": "Lit", "correct": "B", "difficulty": "advanced"},
        {"q": "Ile wynosi prędkość światła w próżni?", "a": "299 792 km/s", "b": "300 000 km/s", "c": "299 792 458 m/s", "correct": "C", "difficulty": "advanced"},
        {"q": "Kto odkrył promieniotwórczość?", "a": "Marie Curie", "b": "Henri Becquerel", "c": "Ernest Rutherford", "correct": "B", "difficulty": "advanced"},
    ],

    "Historia Polski": [
        {"q": "W którym roku Polska odzyskała niepodległość?", "a": "1918", "b": "1919", "c": "1920", "correct": "A", "difficulty": "easy"},
        {"q": "Kto był pierwszym królem Polski?", "a": "Bolesław Chrobry", "b": "Mieszko I", "c": "Kazimierz Wielki", "correct": "A", "difficulty": "easy"},
        {"q": "W którym roku nastąpił chrzest Polski?", "a": "966", "b": "1000", "c": "1025", "correct": "A", "difficulty": "easy"},
        {"q": "Kto był ostatnim królem Polski?", "a": "Stanisław August Poniatowski", "b": "Jan III Sobieski", "c": "August III", "correct": "A", "difficulty": "medium"},
        {"q": "W którym roku odbyła się bitwa pod Grunwaldem?", "a": "1410", "b": "1420", "c": "1430", "correct": "A", "difficulty": "medium"},
        {"q": "Kto dowodził w bitwie pod Grunwaldem?", "a": "Kazimierz Wielki", "b": "Władysław Jagiełło", "c": "Stefan Batory", "correct": "B", "difficulty": "medium"},
        {"q": "W którym roku nastąpił pierwszy rozbiór Polski?", "a": "1772", "b": "1793", "c": "1795", "correct": "A", "difficulty": "advanced"},
        {"q": "Kto był hetmanem koronnym podczas potopu szwedzkiego?", "a": "Stefan Czarniecki", "b": "Stanisław Koniecpolski", "c": "Jan Karol Chodkiewicz", "correct": "A", "difficulty": "advanced"},
        {"q": "W którym roku uchwalono Konstytucję 3 Maja?", "a": "1789", "b": "1791", "c": "1793", "correct": "B", "difficulty": "advanced"},
        {"q": "Kto dowodził powstaniem styczniowym?", "a": "Romuald Traugutt", "b": "Ludwik Mierosławski", "c": "Marian Langiewicz", "correct": "A", "difficulty": "advanced"},
    ],

    "Sport": [
        {"q": "Ile zawodników jest w drużynie piłkarskiej na boisku?", "a": "10", "b": "11", "c": "12", "correct": "B", "difficulty": "easy"},
        {"q": "Gdzie odbyły się pierwsze nowożytne igrzyska olimpijskie?", "a": "Paryż", "b": "Londyn", "c": "Ateny", "correct": "C", "difficulty": "easy"},
        {"q": "Ile punktów wart jest touchdown w futbolu amerykańskim?", "a": "6", "b": "7", "c": "8", "correct": "A", "difficulty": "easy"},
        {"q": "Który polski sportowiec zdobył złoto olimpijskie w rzucie młotem?", "a": "Tomasz Majewski", "b": "Anita Włodarczyk", "c": "Robert Korzeniowski", "correct": "B", "difficulty": "medium"},
        {"q": "Ile setów trzeba wygrać w tenisie na Wielkim Szlemie (mężczyźni)?", "a": "2", "b": "3", "c": "4", "correct": "B", "difficulty": "medium"},
        {"q": "Który klub piłkarski ma najwięcej Pucharów Europy/Ligi Mistrzów?", "a": "Barcelona", "b": "Real Madryt", "c": "Milan", "correct": "B", "difficulty": "medium"},
        {"q": "Kto zdobył najwięcej medali olimpijskich w historii?", "a": "Usain Bolt", "b": "Michael Phelps", "c": "Paavo Nurmi", "correct": "B", "difficulty": "advanced"},
        {"q": "W którym roku Polska wygrała ME w piłce nożnej juniorów?", "a": "Nigdy", "b": "1993", "c": "2001", "correct": "A", "difficulty": "advanced"},
        {"q": "Ile Grand Slamy wygrał Roger Federer?", "a": "18", "b": "20", "c": "22", "correct": "B", "difficulty": "advanced"},
        {"q": "Kto jest najlepszym strzelcem w historii piłki nożnej?", "a": "Pelé", "b": "Cristiano Ronaldo", "c": "Lionel Messi", "correct": "B", "difficulty": "advanced"},
    ],
}
